version: '3'

services:
  server:
    container_name: catmed
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /code/entrypoint.sh
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - "8001:8001"
    environment:
      DEBUG: "False"
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/" ]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  static_volume: { }