version: '3.12'

services:
  server:
    container_name: catmed
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /code/entrypoint.sh
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - "8001:8001"
    environment:
      DEBUG: "False"
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8001/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  static_volume: { }