version: '3.8'

services:
  web:
    build: .
    command: sh -c "ls -R /code && python manage.py migrate && gunicorn --bind ${DJANGO_HOST}:${DJANGO_PORT} catmed.wsgi:application"
    volumes:
      - .:/code

    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
#    env_file:
#      - .env
#    depends_on:
#      - db

#  db:
#    image: postgres:13
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#
#volumes:
#  postgres_data:
