# Generated by Django 4.2.15 on 2024-08-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_medicationtype_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BodyOrgan",
            new_name="Organ",
        ),
        migrations.RenameField(
            model_name="medicine",
            old_name="body_organs",
            new_name="organs",
        ),
    ]
