# Generated by Django 4.2.15 on 2024-08-30 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_rename_bodyorgan_organ_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organ",
            options={"ordering": ["name"]},
        ),
    ]
