# Generated by Django 4.2.16 on 2024-12-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_organ_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentingform",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
