# Generated by Django 4.2.16 on 2024-12-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_presentingform_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineproduct",
            name="buy_place",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pharmacy", "Pharmacy"),
                    ("herbal_shop", "Herbal Shop"),
                    ("website", "Website"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
