# Generated by Django 4.2.17 on 2025-01-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_medicineproduct_buy_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineproduct",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
