# Generated by Django 4.2.17 on 2025-01-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_medicineproduct_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineproduct",
            name="currency",
            field=models.CharField(
                choices=[("RON", "RON"), ("USD", "USD"), ("EUR", "EUR")],
                default="RON",
                max_length=10,
            ),
        ),
    ]
