# Generated by Django 4.2.17 on 2025-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_medicineproduct_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineproduct",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("RON", "RON"), ("USD", "USD"), ("EUR", "EUR")],
                default="RON",
                max_length=10,
                null=True,
            ),
        ),
    ]
