# Generated by Django 4.2.17 on 2025-01-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_medicineproduct_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineproduct",
            name="product_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
