# Generated by Django 4.2.17 on 2025-01-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_medicineproduct_product_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineproduct",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
