name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11 ] # Add other versions if needed

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set environment variables
        run:
          echo "SECRET_KEY=$(openssl rand -hex 32)" >> $GITHUB_ENV

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Run Tests
        run: |
          pytest

#      - name: Run Coverage
#        run: |
#          coverage run -m pytest -m "not production_inaccessible" -x
#          coverage report -m
#          coverage xml
#
#      - name: Upload Coverage to Codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          name: codecov-umbrella
